# -*- coding: utf-8 -*-
{   'active': False,
    'author': u'ADHOC SA',
    'category': u'base.module_category_knowledge_management',
    'data': [   u'security/law_tracking_group.xml',
                u'view/legislature_view.xml',
                u'view/treatment_detail_view.xml',
                u'view/commission_treatment_view.xml',
                u'view/commission_position_view.xml',
                u'view/log_view.xml',
                u'view/law_project_document_view.xml',
                u'view/enclosure_treatment_detail_view.xml',
                u'view/order_paper_view.xml',
                u'view/law_project_view.xml',
                u'view/legislature_member_view.xml',
                u'view/commission_detail_view.xml',
                u'view/partner_view.xml',
                u'view/block_view.xml',
                u'view/subscription_view.xml',
                u'data/legislature_properties.xml',
                u'data/treatment_detail_properties.xml',
                u'data/commission_treatment_properties.xml',
                u'data/commission_position_properties.xml',
                u'data/log_properties.xml',
                u'data/law_project_document_properties.xml',
                u'data/enclosure_treatment_detail_properties.xml',
                u'data/order_paper_properties.xml',
                u'data/law_project_properties.xml',
                u'data/legislature_member_properties.xml',
                u'data/commission_detail_properties.xml',
                u'data/partner_properties.xml',
                u'data/block_properties.xml',
                u'data/subscription_properties.xml',
                u'data/legislature_track.xml',
                u'data/treatment_detail_track.xml',
                u'data/commission_treatment_track.xml',
                u'data/commission_position_track.xml',
                u'data/log_track.xml',
                u'data/law_project_document_track.xml',
                u'data/enclosure_treatment_detail_track.xml',
                u'data/order_paper_track.xml',
                u'data/law_project_track.xml',
                u'data/legislature_member_track.xml',
                u'data/commission_detail_track.xml',
                u'data/partner_track.xml',
                u'data/block_track.xml',
                u'data/subscription_track.xml',
                u'workflow/commission_treatment_workflow.xml',
                u'workflow/order_paper_workflow.xml',
                u'workflow/legislature_member_workflow.xml',
                u'workflow/subscription_workflow.xml',
                'security/ir.model.access.csv',
                u'view/law_tracking_menuitem.xml'],
    'depends': [u'mail'],
    'description': u'Law Follow Up',
    'installable': True,
    'license': 'AGPL-3',
    'name': u'Law Follow Up',
    'test': [],
    'version': '8.0.1.1.0',
    'website': ''}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
